######################################################################
# Automatically generated by qmake (2.01a) Sze márc. 27 22:09:44 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += frakablak.h frakszal.h
SOURCES += bio.cpp frakablak.cpp frakszal.cpp main.cpp mandel.cpp mandelkomp.cpp
